UI: Updating time filters
google/timesketch pull request #1365
Opened 2020-09-10 05:17 UTC by binglot

Allow the users to update the time filters that they've created by clicking on them. Also added some UX improvements, such as closing the dropdown when the filter is added/updated, or auto-populating the end time input based on the start time.

2020-09-16 13:24 UTC, berggren requested changes

2020-09-16 13:24 UTC, berggren commented on timesketch/frontend/src/components/Sketch/TimeFilter.vue
> +      event.target.parentNode.parentNode.parentNode.getElementsByClassName('input')[1].focus()
This is a little difficult to follow. If you need to get the DOM element you can use the Ref. See this for an example:
https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

2020-09-16 13:24 UTC, berggren commented on timesketch/frontend/src/components/Sketch/TimeFilter.vue
> +      this.$parent.$parent.isActive = false;
This is difficult to reason about. What prop is being mutated here? In what component. Can you emit an event and catch that in the calling component instead?

2020-09-16 13:24 UTC, berggren commented on timesketch/frontend/src/components/Sketch/TimeFilter.vue
> +      this.$parent.$parent.isActive = false;
Same here

2020-09-16 13:25 UTC, berggren commented
First round done, @binglot PTAL

2020-09-22 01:43 UTC, binglot commented
@berggren - ready for the 2nd round of review :)

2020-09-22 06:09 UTC, berggren approved these changes
LGTM

2020-09-22 06:09 UTC, merged