Deprecated the option to import timelines in tsctl.
google/timesketch pull request #1594
Opened 2021-02-06 13:47 UTC by kiddinn

With the new way of uploading data to Timesketch (#1567) it is hard to support `tsctl` as well as the importer and the upload resources in the API.

Therefore this PR will just deprecate the option of using tsctl to import data in favor of the importer client. Tsctl will rather be used for administrative tasks to Timesketch.

2021-02-06 15:51 UTC, kiddinn commented
This is part of #1567

2021-02-08 07:23 UTC, berggren requested changes

2021-02-08 07:23 UTC, berggren commented on timesketch/tsctl.py
> +            'timesketch_importer instead.')
```suggestion
            'timesketch_importer instead: https://github.com/google/timesketch/blob/master/docs/UploadData.md')
```

2021-02-08 07:51 UTC, berggren approved these changes

2021-02-08 07:57 UTC, merged