Fixing issue #1733
google/timesketch pull request #1756
Opened 2021-04-30 12:34 UTC by warrinot

Fixing issue #1733.
This is my first open-source issue, please tell me if i did something wrong.

2021-04-30 13:42 UTC, kiddinn requested changes
thank you for the patch, made a minor suggestion

2021-04-30 13:42 UTC, kiddinn commented on api_client/python/timesketch_api_client/sketch.py
> +                duplicate_attributes.append(key)
for this you could also just have done

```python
duplicate_attributes = [k for k in attributes if k in form_data]
```

that is do that in a single line using list comprehension

2021-04-30 13:48 UTC, kiddinn reviewed
forgot one thing

2021-04-30 13:48 UTC, kiddinn commented on api_client/python/timesketch_api_client/sketch.py
> +                f'Following attributes cannot overwrite values already set: {duplicates}')
there is a linter issue here...

2021-05-03 12:51 UTC, closed without merging

2021-05-03 13:04 UTC, kiddinn commented
Why did you close this PR?

2021-05-03 17:02 UTC, warrinot commented
I was not sure if you could see my changes and messed up with commits a bit.