Changed how sketch attributes are handled.
google/timesketch pull request #1792
Opened 2021-05-27 10:19 UTC by kiddinn

This PR changes few ways on how sketch attributes are handled:

1. Attributes are returned as a dict as an opposed to a list of tuples
2. Attributes can be modified, instead of just added/deleted
3. REST API now uses HTTP methods to determine whether you are adding/modifying or deleting, vs. relying on a `action` variable

2021-05-27 12:06 UTC, tomchop requested changes

2021-05-27 12:06 UTC, tomchop commented on timesketch/api/v1/utils.py
> +            attributes[name] = (attribute_values[0], ontology_string)
don't we want something like

```python
attributes.append({
  'name': name,
  'value': attribute_values[0],
  'ontology': ontology_string
})
```

or

```python
attributes[name] = {
  'value': attribute_values[0],
  'ontology': ontology_string
}
```

2021-05-27 16:27 UTC, kiddinn commented
this is ready for a review, @tomchop PTAL

2021-05-28 09:44 UTC, tomchop approved these changes

2021-05-28 09:51 UTC, merged