Better tag rendering in intelligence view
google/timesketch pull request #2123
Opened 2022-01-26 12:27 UTC by tomchop

This PR makes tag rendering a bit nicer in the intelligence view, prioritizing some tags given a pre-defined wieght and color class.

Additionally, constants such as `IOCTypes` were moved to their own file to avoid code duplication.

2022-02-01 15:04 UTC, berggren requested changes
Just a small naming issue

2022-02-01 15:04 UTC, berggren commented on timesketch/frontend/src/views/Intelligence.vue
> +                        <router-link :to="{ name: 'Explore', query: generateOrElasticQuery(tagInfo[tag.name].iocs) }">
Please refactor to name this `generateOrOpenSearchQuery`

2022-02-01 15:04 UTC, berggren commented on timesketch/frontend/src/views/Intelligence.vue
> +    generateOrElasticQuery(valueList) {
```suggestion
    generateOrOpenSearchQuery(valueList) {
```

2022-02-01 15:04 UTC, berggren commented on timesketch/frontend/src/views/Intelligence.vue
>      generateElasticQuery(value, field) {
```suggestion
    generateOpenSearchQuery(value, field) {
```

2022-02-06 11:47 UTC, berggren commented
PTAL @tomchop

2022-02-07 16:43 UTC, tomchop commented
PTAL @ [4f1fca0](https://github.com/google/timesketch/pull/2123/commits/4f1fca0b6c7dfacf1d80ba6b8a3ecd09fb19397c) (add tag coloring and sorting to bottom left pane) and [d56ec5e](https://github.com/google/timesketch/pull/2123/commits/d56ec5ea19b46e050a8cb6f47779d1862da20da0) (refactor names)

2022-02-08 09:12 UTC, berggren approved these changes
LGTM

2022-02-08 09:12 UTC, merged