Use all rules in the analyzer
google/timesketch pull request #2202
Opened 2022-06-02 14:19 UTC by jaegeral

Adding functionality in the analyzer code for Sigma to use rules that are considered "bad" in the status csv but limiting the attributes it would add to ts_sigma_filename.

Right now we struggle to find out which rule is how noisy, to do that, we would need to run every rule query over a sketch every time it is visited, which could result in 1000 queries over all timelines just to get a count.

To preserve that count, the analyzer would use all the rules installed on a system, but only add User visible tags / labels for those that are considered "good".

By reverse referencing the rule name with the status csv we could in the future run a cleanup job to remove noisy entries from events if we choose to.

Alternative would be to store the count results in a database somewhere.

https://github.com/google/timesketch/issues/2201

2022-06-03 09:15 UTC, tomchop requested changes

2022-06-03 09:15 UTC, tomchop commented on timesketch/lib/analyzers/sigma_tagger.py
> +            # if rule.get('ts_use_in_analyzer') is True:
Please remove this commented-out code. (or add an actual comment)

2022-06-03 09:15 UTC, tomchop commented on timesketch/lib/analyzers/sigma_tagger.py
> +                # ad the remaining tags as plain tags
```suggestion
                # add the remaining tags as plain tags
```

2022-06-03 09:15 UTC, tomchop commented on timesketch/lib/analyzers/sigma_tagger.py
> +                    # Special handling for sigma tags that TS considers TTPS
```suggestion
                    # Special handling for sigma tags that TS considers TTPs
```

2022-06-03 09:15 UTC, tomchop commented on timesketch/lib/analyzers/sigma_tagger.py
> +            status_good: value from sigma_status.csv good / bad / exploratory
This makes it sound as if we expect a string, but we're using a boolean here, so the comparison has to be made by the caller.

2022-06-03 09:15 UTC, tomchop commented on timesketch/lib/analyzers/sigma_tagger.py
> +    ):
```suggestion
        self, query, rule_name, tag_list=None, status_good=True):
```

2022-06-03 13:20 UTC, jaegeral reviewed
feedback

2022-06-03 13:21 UTC, jaegeral reviewed
feedback

2022-06-03 15:16 UTC, tomchop approved these changes

2022-06-03 15:31 UTC, merged

2022-06-06 07:48 UTC, tconqueror commented
Can i get a sample of sigma_rule_status.csv, it cause http status 404 when access sketch if sigma_rule_status.csv not exist

2022-06-07 04:19 UTC, tconqueror commented
> > Can i get a sample of sigma_rule_status.csv, it cause http status 404 when access sketch if sigma_rule_status.csv not exist
> 
> Hey hey, the file in question is part of the PR: https://github.com/google/timesketch/blob/master/data/sigma_rule_status.csv
> 
> You need to add the new config value as well. Hope that helps

Yeah, thank you very much!