build(deploy_timesketch.sh): add script options and flag for starting container
google/timesketch pull request #2220
Opened 2022-06-15 23:07 UTC by harshalchaudhari35

This pull request addresses the issue #1840 

+ What existing problem does this PR solve?
Inline with some previous discussion/comments from the maintainers, have considered to add flag and options to the bash script to provide fine grained control to the user, i.e to start timesketch container and create a new user.

p.s. hope I have not over-engineered the solution

**Checks**
- [X] Tested locally for the conditional parts of the bash script

2022-06-20 15:42 UTC, berggren requested changes
Thanks for contributing! Looks good. PTAL

2022-06-20 16:03 UTC, harshalchaudhari35 commented on contrib/deploy_timesketch.sh
> +      sleep 0.1;
fair point :)

2022-06-20 16:04 UTC, harshalchaudhari35 commented on contrib/deploy_timesketch.sh
> +START_CNTR=
done

2022-07-08 13:23 UTC, harshalchaudhari35 commented
@berggren gentle nudge on this one, think I've addressed the review comments.

2022-08-01 10:05 UTC, berggren approved these changes
LGTM. Thanks for contributing!

2022-08-01 10:29 UTC, merged