PINFO ERROR MESSAGE AND EXTENSION FORMAT
google/timesketch pull request #2343
Opened 2022-09-27 08:21 UTC by marcobrotto

# Solving some bugs related to PR 2326

1. Extension of file with "multiple dots": the extension in `uploadForm.vue` is computed as the last substring of the array `extensionArray = filename.split('.')`.
2. When `pinfo.py` cannot run on the server (see `tasks.py`) the server set the datasource status as `fail` and an error message is returned to the client.
3. Minor changes: a timeline with a fail status does not trigger the command `this.$emit('toggle', response.data.objects[0])` (see `Timelinechip.vue`)

2022-09-27 08:23 UTC, marcobrotto commented on timesketch/frontend-ng/src/views/Explore.vue
> +          <v-btn small icon @click="addEventBtn(item._source.datetime)">
This is the button to insert a manual event related to an existing event. With the previous PRs it was accidentally removed.

2022-09-27 11:39 UTC, berggren requested changes

2022-09-27 11:39 UTC, berggren commented on timesketch/lib/tasks.py
> +        )
This will close the whole index, making all other datasources that uses this index non-functional. Is that what we want here?

2022-09-27 11:39 UTC, berggren commented on timesketch/lib/tasks.py
> +        )
Same here - I guess we only want to mark the timeline as fail, but keep the index open?

2022-09-28 17:48 UTC, berggren requested changes

2022-09-29 14:32 UTC, berggren approved these changes
LGTM

2022-09-29 14:59 UTC, merged

2022-09-29 20:44 UTC, Zawadidone commented
Since this merge a few JSONL timelines imported by the Timesketch importer keep haning on "Indexing in progress.." while the worker tasks are already finished. Is it possible this PR caused a bug?

<img width="283" alt="image" src="https://user-images.githubusercontent.com/21525407/193138159-6d46f965-7fd0-4ed4-b802-1491ae64c841.png">