Allow additional OIDC domains to access ap is when o aith is used
google/timesketch pull request #2421
Opened 2022-11-09 17:15 UTC by sa3eed3ed

Allow multiple OIDC domains to be authenticated when calling APIs in OAuth mode. Add a new list of allowed domains to server config and change the login verification to determine if the email in the ID token belongs to any of the allowed domains.

closes #2420

2022-11-11 09:02 UTC, berggren requested changes

2022-11-11 09:02 UTC, berggren commented on timesketch/views/auth.py
> +    ALLOWED_DOMAINS = list(map(lambda x: x.lower(), allowed_domains))
To stay consistent with the style in the project, we favour list comprehensions over lambdas when possible.
 ```suggestion
    ALLOWED_DOMAINS = [domain.lower() for domain in allowed_domains]
```

2022-11-11 09:45 UTC, sa3eed3ed commented on config/dpkg/timesketch-server.timesketch.default
> +GOOGLE_OIDC_API_ALLOWED_DOMAINS = None
```suggestion
GOOGLE_OIDC_API_ALLOWED_DOMAINS = []
```

2022-11-11 09:46 UTC, sa3eed3ed commented on timesketch/views/auth.py
> +   ALLOWED_DOMAINS = [domain.lower() for domain in allowed_domains]
```suggestion
    ALLOWED_DOMAINS = [domain.lower() for domain in allowed_domains]
```

2022-12-13 19:49 UTC, berggren approved these changes
LGTM

2022-12-13 19:49 UTC, merged