timesketch_api_clietn: Expose all items from DB instead of arbitrary subset.
google/timesketch pull request #2504
Opened 2023-01-05 17:16 UTC by tomchop

This change brings more data into what can be received by the Python API client.

2023-01-10 09:17 UTC, berggren requested changes

2023-01-11 08:43 UTC, tomchop commented on api_client/python/timesketch_api_client/sketch.py
> +                    result["status"] = status[0].get("status", "N/A")
They're nested into a timeline field. Is that OK, or do you want me to duplicate them to first-level so that we retain the same functionality?

2023-03-17 10:03 UTC, jaegeral commented on api_client/python/timesketch_api_client/sketch.py
> +                    result["status"] = status[0].get("status", "N/A")
I would opt to keep them as they where before, or are we sure no one is using those fields in any tool downstream?

2023-03-21 07:10 UTC, berggren requested changes

2023-03-21 07:10 UTC, berggren commented on api_client/python/timesketch_api_client/sketch.py
@tomchop Can you elaborate on why this change is necessary and what the use case is? There may be colabs and tools depending on the output here so I want to make sure it is warranted.

2023-03-21 07:11 UTC, berggren commented
Added @jkppr to review form the analysis side.

2023-03-21 14:52 UTC, tomchop commented
Let's close this for now, as I don't remember exactly what my use-case was. If I ever run into it again, I'll make sure to reopen and address comments.

2023-11-14 16:09 UTC, jkppr commented
Re-opening this PR, since we finally remember why we needed this change. 
* Use-case: Make the timesketch api client compatible with the dftimewolf timesketch module that handles analyzer results & status.
* The change was tested internally for ~10 month now, without any known problems "downstream". 

Next step: Test & merge the change.

2023-11-14 16:21 UTC, jkppr commented on api_client/python/timesketch_api_client/sketch.py
This change is necessary to improve the dftimewolf support on reporting about analyzer status. Internal testing has shown no known problems with tools downstream so far.

2023-11-14 16:25 UTC, jkppr commented on api_client/python/timesketch_api_client/sketch.py
> +                    result["status"] = status[0].get("status", "N/A")
* Internal testing showed that there are no problems "downstream" that we are aware of.
* This change also allows access to richer information about the timesketch analyzer result by exposing the full result object without static formatting.

2023-11-14 16:25 UTC, jkppr approved these changes
LGTM

2023-11-14 16:27 UTC, merged