SSH Brute Force Analysis
google/timesketch pull request #2511
Opened 2023-01-11 22:11 UTC by roshanmaskey

This PR adds `SSHBruteForcePlugin` (`ssh_bruteforce.py`) that analysis SSH authentication events and provides the summary of brute force analysis report and automatically tags the relevant events. 

**SSHBruteForcePluing Result**

The figure below shows the result of the analyzer.

<img width="1322" alt="sshbruteforceplugin_result" src="https://user-images.githubusercontent.com/10503312/211926969-76861dc4-8fc5-436c-8ea8-7da8c5d3bbf5.png">

**Labeled Events**

The figure below shows relevant SSH events labeled and stared.

<img width="1316" alt="sshbruteforceplugin_label" src="https://user-images.githubusercontent.com/10503312/211928464-0a072bd5-55f2-470f-9d58-679a86063c18.png">

**Checks**

- [x] All tests succeed.
- [x] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

2023-01-12 13:20 UTC, berggren commented
Ack, I will review asap.

2023-01-13 15:45 UTC, berggren commented
Hey @roshanmaskey good stuff! I started looking at this today, and I have a couple of higher level thoughts.

- Maybe consider refactor to a proper plugin system for authentication analyzers (see the chain analyzers for example)
- The use of pyparsing - I'm wondering if we already have some of this data extracted via plaso? And if not, should we add it there?

I'll set up a sync for us together with @jkppr to progress this asap.

2023-03-21 07:12 UTC, berggren commented
Adding @jkppr to review from the analysis side

2023-04-04 14:31 UTC, jkppr reviewed
As discussed offline: This PR will get some more work by @roshanmaskey with new ideas and approaches from the last month.
Main points are:
* Update the demo data to be compatible with the newest Timesketch/Plaso version
* If possible make use of the `syslog` plaso parser to extract the necessary fields. This would allow to skip the usage of pyparsing.
* If field  parsing is necessary, check out the feature extractor function to take care of this before running your analyzer.

2023-04-07 12:22 UTC, roshanmaskey commented
@jkppr ready for review.

2023-04-14 14:43 UTC, jkppr requested changes
First round of comments.
I need a bit more time to think about the usage of pyparsing and if we could archive the same goal using the feature extractor. I will come back to this in round 2 then :)

2023-04-14 14:43 UTC, jkppr commented on timesketch/lib/analyzers/auth.py
Let's discuss in our next 1:1 the pro & cons of building this as an analyzer plugin system.

2023-04-14 14:43 UTC, jkppr commented on timesketch/lib/analyzers/ssh_bruteforce_test.py
> +# -*- coding: utf-8 -*-
Not needed in python 3 anymore.

2023-04-14 14:43 UTC, jkppr commented on timesketch/lib/analyzers/ssh_bruteforce.py
> +# -*- coding: utf-8 -*-
Not needed in python 3 anymore.

2023-05-12 06:47 UTC, closed without merging