Making timestamp leading value when importing a csv
google/timesketch pull request #2586
Opened 2023-02-28 09:11 UTC by jaegeral

This PR changes the CSV import handling from using datetime as the leading value to using timestamp. 

It also calculates an offset between datetime and the provided timestamp to see if the values are too far apart.

The new code will first check if the row of the CSV file contains a timestamp. If it does, then it will use that timestamp as the leading value and calculate a datetime value.

The code will also calculate an offset between the datetime and the provided timestamp. This offset will be used to determine if the values are too far apart. If the offset is greater than a certain threshold, then the code will raise an error and create the datetime value based on the provided timestamp.

The PR also introduces a new csv with some test data that I hope we will increase over time. I opted to not make it mocked in the unit tests itself so that we can re-use the csv later in end2end tests or if someone needs test data with problems.

*Note:* As far as I can tell, in Importing JSON part of the util class, the timestamp is already the "leading" value - so this change will just get it to similar approach. But the JSOn import does not have a check yet on how far provided values are apart. 

**Checks**

- [x] All tests succeed.
- [x] Unit tests added.
- [x] e2e tests added.
- [x] Documentation updated.

**Closing issues**

closes #2579

2023-02-28 13:42 UTC, jaegeral commented on timesketch/lib/utils_test.py
> +    def test_datetime_parsing_csv_file(self):
This is the only real new thing in the unit tests, rest is only black formatting

2023-03-10 08:25 UTC, berggren requested changes

2023-03-10 08:25 UTC, berggren commented on timesketch/lib/utils.py
> +                MAX_TIMESTAMP_DIFFERENCE = 100000  # 100 seconds
As discussed offline - Instead of rewriting the fualty datetime we should error out and let the user fiox the broken input.

2023-03-16 13:00 UTC, berggren approved these changes
LGTM, with one small nit.

2023-03-16 13:00 UTC, berggren commented on timesketch/lib/utils.py
> +                    # convert row datetime to timestamp
The comment doesn't add value IMO

2023-03-16 13:00 UTC, berggren commented
Take a look at the failing e2e test

2023-03-16 13:01 UTC, berggren requested changes
failing e2e test. Please fix before merge

2023-03-16 14:21 UTC, berggren approved these changes

2023-03-16 14:39 UTC, merged