Initial submit to add a verbose and json output to the explore method…
google/timesketch pull request #2607
Opened 2023-03-09 16:20 UTC by jaegeral

Add a verbose flag to the search method in Timesketch CLI and a new output format for the same method.

This enables analysts to output the raw timeline with OpenSearch Internals:

```
timesketch search --limit 20 --verbose --output-format json |jq .
{
  "__ts_timeline_id": 16,
  "comment": [],
  "datetime": 0,
  "message": "3QPcr6sadN",
  "timestamp": 0,
  "timestamp_desc": "Last Time Executed",
  "_id": "R6R9eYYBGeSzWlvssgk2",
  "_type": "_doc",
  "_index": "bfdc00e7d59f462a905de807cc1b35dc",
  "_source": null
}
```

2023-03-09 17:06 UTC, jaegeral commented
Adding @berggren  here as he might have opinions on the new verbose flag

2023-03-16 12:41 UTC, berggren requested changes

2023-03-16 12:41 UTC, berggren commented on cli_client/python/timesketch_cli_client/commands/search.py
--verbose is a bit ambiguous in this context. I opt that we are more direct.
I prefer `--show-internal-columns` as the flag instead. This is describing what it does, and is similar to the other flag `--show-headers`

2023-03-16 14:23 UTC, berggren approved these changes

2023-03-16 14:34 UTC, merged