Minor fixes for AggregateDialog
google/timesketch pull request #2726
Opened 2023-05-06 03:00 UTC by sydp

This PR adds some minor fixes:

* fixes an off-by-one bug in the hour-day aggregation
* removes items per page table option for rare values.

- [ ] All tests succeed.
- [ ] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

**Closing issues**
* Closes #2697 
* Closes #2685

2023-05-08 13:42 UTC, jkppr requested changes
Generally looks good, I just noticed one breaking change. Please take a look below.

2023-05-08 13:42 UTC, jkppr commented on timesketch/frontend-ng/src/components/Explore/AggregateDialog.vue
When I try these changes in my dev env, my aggregations break with the following error in this component:
```
TypeError: Cannot read properties of undefined (reading 'buckets')
    at o.intervalChartOptions (AggregateDialog.vue:332:1)
    at t.get (vue.runtime.esm.js:3446:33)
    at t.evaluate (vue.runtime.esm.js:3547:27)
    at o.intervalChartOptions (vue.runtime.esm.js:5537:25)
    at o.ie (AggregateDialog.vue:1:7722)
    at Dn.t._render (vue.runtime.esm.js:2684:28)
    at o.r (vue.runtime.esm.js:3875:27)
    at t.get (vue.runtime.esm.js:3446:33)
    at t.run (vue.runtime.esm.js:3522:30)
    at Jr (vue.runtime.esm.js:4121:17)
```

2023-05-09 11:11 UTC, jkppr requested changes
Thanks for fixing the error. I noticed one more issue below.

2023-05-09 11:11 UTC, jkppr commented on timesketch/frontend-ng/src/components/Explore/AggregateDialog.vue
The DataLabels for the `Event distribution by` chart can get a bit crowded when selecting the year scope (see screenshot below). It also generates the following warning:
```
WARNING: DataLabels are enabled but there are too many to display. This may cause performance issue when rendering.
```

![TS_agg_v2_labels](https://github.com/google/timesketch/assets/99879757/b640321e-3a71-4e30-9d55-ca7860e9167c)

Can this be fixed by e.g. showing just a subset of data labels for orientation?

2023-05-10 11:19 UTC, sydp commented on timesketch/frontend-ng/src/components/Explore/AggregateDialog.vue
I set the max number of labels to 12 for this graph and on my test data/instance it doesn't overlap and I seem to no longer get that warning message.  how does it look on your end?

2023-05-10 12:34 UTC, jkppr commented on timesketch/frontend-ng/src/components/Explore/AggregateDialog.vue
I still get the warning for attributes that have data spanning many years, but this is not blocking from my point of view.
The solution with 12 labels looks great 👍

2023-05-24 11:27 UTC, berggren approved these changes

2023-05-24 11:29 UTC, merged