Windows bruteforce analyzer
google/timesketch pull request #2792
Opened 2023-06-11 08:16 UTC by roshanmaskey

This PR is related to issue # 2791

This PR adds support to determine successful windows login related to brute force activity. If a successful login is preceded by at least 20 failed login attempts from a given IP address within 3600 seconds, the analyzer will mark them as a brute force attempts.

**Checks**

- [x] All tests succeed.
- [x] Unit tests added.
- [x] e2e tests added.
- [ ] Documentation updated.

**Closing issues**

Put `closes #2791` in your comment to auto-close the issue that your PR fixes
(if such).

2023-06-12 16:58 UTC, jkppr requested changes
Please check the comments below.

2023-06-12 16:58 UTC, jkppr commented on timesketch/lib/analyzers/authentication/windows.py
> +                event.add_label("windows_bruteforce")
```suggestion
                event.add_tags(["windows_bruteforce"])
```
`add_label` is deprecated. Please use `add_tags` only.

2023-06-14 07:11 UTC, roshanmaskey commented on timesketch/lib/analyzers/authentication/windows.py
> +                log.warning("[%s] Unknown value for logon_type. %s", self.NAME, str(e))
Changed to debug.

2023-06-14 08:16 UTC, jkppr requested changes

2023-06-14 08:16 UTC, jkppr commented on timesketch/lib/analyzers/authentication/windows.py
> +            log.error("[%s] Unable to annotate. %s", self.NAME, str(e))
This error is logged but seems to have no impact for the analyzer. If nothing should happen when this error is triggered, it is probably worth to change it to a debug level. If the error is important to the analyzer results, I would recommend to update the analyzer output object and set the results_status to ERROR and describe why this analyzer failed.

2023-06-16 16:01 UTC, jkppr approved these changes
lgtm

2023-06-16 16:01 UTC, merged