Added necessary tooltips to icons in new frontend
google/timesketch pull request #2952
Opened 2023-10-21 02:55 UTC by bryankhor07

+ What existing problem does this PR solve?
It adds tooltips to icons that need a short description.

**Checks**

- [x] All tests succeed.
- [x] Unit tests added.
- [x] e2e tests added.
- [x] Documentation updated.

**Closing issues**

Closes #2693

2023-10-25 08:56 UTC, jkppr requested changes
First round review:
* Thanks for contributing and tackling the tooltip task.
* Please consider working from a separate branch in your fork and not from master.
* Please keep your PR clean and do not submit files that are not necessary or related to the fix you are working on.
* Please see the comments below.

2023-10-25 08:56 UTC, jkppr commented on timesketch/frontend-ng/src/views/Home.vue
> +              <v-icon title="Action Menu">mdi-dots-vertical</v-icon>
```suggestion
              <v-icon title="Sketch menu">mdi-dots-vertical</v-icon>
```

2023-10-25 08:56 UTC, jkppr commented on timesketch/frontend-ng/src/views/Sketch.vue
> +        <v-icon title="Manage">mdi-menu</v-icon>
```suggestion
        <v-icon title="Toggle left panel">mdi-menu</v-icon>
```

2023-11-03 16:00 UTC, gstgrace commented
Hi @jkppr , thanks for checking in! Yes, we are still revising the code based on the feedback.

2023-11-17 15:27 UTC, jkppr commented
I forked this PR and finished it, since some UX guidance changed mid-way and we want to have it ready for the next release in December. Therefore closing this PR in favor of #2983 .

Thanks for contributing @gstgrace @bryankhor07  @lemonshark05

2023-11-17 15:27 UTC, closed without merging