Removing old feature extractor analyzer
google/timesketch pull request #2969
Opened 2023-11-02 15:33 UTC by jkppr

This PR removes the "old" feature extractor analyzer and replaces it with the new feature extraction plugin analyzer. The "old" regex based analyzer was moved into the new plugin one as part of #2910 .

* Removes the "old" feature extraction analyzer.
* Removes the old `feature.yaml` config to `regex_features.yaml` to better reflect its purpose.
  * The analyzer is backwards compatible with the old filename. The new one will be preferred though. 
* Removes regex based extractions from the `regex_features.yaml`config that are now covered by the new `winevt_features.yaml` config.
* Takes care of dependency naming within the analyzers.
* Flips the run order for plugins: regex first, then the rest.
* Adds a small check in the winevt extraction plugin to add info comments only if they do not exist yet.

2023-11-02 15:35 UTC, jkppr commented
@roshanmaskey fyi

2023-11-02 20:39 UTC, berggren requested changes

2023-11-02 20:39 UTC, berggren commented on timesketch/lib/analyzers/feature_extraction_plugin.py
I would keep this named as `feature_extraction.py`. It's not a plugin, it's the main analyzer that runs all the plugins, right?

2023-11-03 07:07 UTC, jkppr commented on timesketch/lib/analyzers/feature_extraction_plugin.py
Sure, works for me as well. I changed it.

2023-11-03 08:28 UTC, berggren approved these changes

2023-11-03 08:28 UTC, merged