Implement user management (create, list, get) via API
google/timesketch pull request #3024
Opened 2024-01-21 21:36 UTC by lo-chr

This PR fixes most of the features, mentioned here: https://github.com/google/timesketch/issues/3023

This PR is a first step into further capabilities of user management via API, although it lacks the ability to manage a particular user itself.

I also added some features to the testing framework, enabling the test of "admin only" tests, via creating admin users during test setup.

**Checks**
- [ ] All tests succeed -> there are some errors in the Sigma Tests, which I did not touch. My added tests did succeed.
- [ X ] Unit tests added.
- [ ] e2e tests added -> no e2e tests, but this is not a complex enhancement.
- [ ] Documentation updated -> change in the API client.

**Closing issues**
closes #3023

2024-01-21 22:00 UTC, lo-chr commented
Giving this PR a bit more thought, I identified some security and data privacy issues. I will set this PR into draft mode again, fix the issues and submit the  PR again. Sorry for the inconvenience.

2024-01-21 22:36 UTC, lo-chr commented
I changed the UserResource, so that it does not check for user privileges anymore.

Might be useful to limit details like mail address to admin users In the future.

2024-01-24 14:10 UTC, berggren commented
Hi @lo-chr thanks for contributing! I'll review this on Friday, Jan 26.

2024-02-01 12:54 UTC, berggren requested changes

2024-02-01 12:54 UTC, berggren commented on api_client/python/timesketch_api_client/client.py
> +            sketch_id: Primary key ID of the sketch.
```suggestion
            user_id: Primary key ID of the user.
```

2024-02-01 12:54 UTC, berggren commented on api_client/python/timesketch_api_client/client.py
> +            Instance of a Sketch object.
```suggestion
            Instance of a User object.
```

2024-02-01 22:15 UTC, lo-chr commented
I'll fix this over the weekend! Thank you for the review.

2024-02-03 16:32 UTC, lo-chr commented on timesketch/api/v1/resources/user.py
> +            )
Changed this with https://github.com/google/timesketch/pull/3024/commits/bc0b8b383da04d1efcef072478f7824b6af539a1

2024-02-06 08:19 UTC, berggren requested changes
PTAL

2024-02-06 08:19 UTC, berggren commented on timesketch/api/v1/resources/user.py
> +        user = User.get_or_create(username=username)
```suggestion
```
You don't have to fetch the User object again, you do it above.

2024-02-06 08:19 UTC, berggren commented on timesketch/api/v1/resources/user.py
> +        return jsonify({"objects": [return_user]})
```suggestion
return self.to_json(user)
```
You have added the fields to the resource field mapping in __init__. You just need to call self.to_json here

2024-02-06 08:19 UTC, berggren commented on timesketch/api/v1/resources/user.py
> +        return jsonify({"objects": [return_user]})
```suggestion
return self.to_json(user)
```

2024-02-06 14:41 UTC, berggren approved these changes
LGTM

2024-02-06 14:41 UTC, berggren commented
Thanks for contributing!

2024-02-06 14:46 UTC, lo-chr commented
Thank your for the reviews and advice. I learned one or two things. ☺️

2024-02-06 19:42 UTC, merged