Added check to invalid API endpoints to close issue #3005
google/timesketch pull request #3058
Opened 2024-03-30 00:42 UTC by TedmanNguyen

This PR improves accessing URL to return 404 for with invalid endpoint instead of 200.
+ Added handle_invalid_routes (in app.py) and unit test: InvalidResourceTest (in resources_test.py)

**Checks**

- [x] All tests succeed.
- [x] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

Closes issue #3005:

2024-04-06 19:07 UTC, mistic01 commented
Code Fix is working as expected - LGTM

2024-04-15 07:36 UTC, jkppr requested changes
Thanks for your PR. Please see the comments and recommended changes below.

2024-04-15 07:36 UTC, jkppr commented on timesketch/app.py
> +        """
```suggestion
        """Error handler for non-existent API routes.

        Raises:
            ApiHTTPError: Error 404 - not found        
        """
```

Updating the doc string to reflect the changes.

2024-04-15 07:36 UTC, jkppr commented on timesketch/app.py
>      return app
```suggestion
    CSRFProtect(app)

    return app
```

Removing empty lines

2024-04-15 07:36 UTC, jkppr commented on timesketch/api/v1/resources_test.py
> +    def test_invalid_endpoint(self):
```suggestion
    invalid_resource_url = "api/v1/invalidresource"

    def test_invalid_endpoint(self):
```

Removing trailing whitespace making the linter happy.

2024-04-24 13:17 UTC, jkppr approved these changes
lgtm from my side. Adding @berggren for the last word.

2024-05-07 08:17 UTC, merged