Create new NL2Q API.
google/timesketch pull request #3073
Opened 2024-04-17 08:22 UTC by dianakramer

+ What existing problem does this PR solve?
Creating queries from natural language questions (following DFIQ).
+ What new feature is being introduced with this PR?
Natural language to query with DFIQ.
+ Overview of changes to existing functions if required.
Creating a new API.

2024-04-26 11:05 UTC, jkppr requested changes
Thanks for adding this great feature! 

Please take care of the comments below.

Also, please add a test for this API endpoint.

2024-04-26 11:05 UTC, jkppr commented on timesketch/api/v1/resources/nl2q.py
> +        """
Please add the parameters to the docstring as "Args:" section.

2024-04-26 11:05 UTC, jkppr commented on timesketch/api/v1/resources/nl2q.py
> +        """
Please add the parameters to the docstring as "Args:" section.

2024-04-26 11:05 UTC, jkppr commented on timesketch/api/v1/resources/nl2q.py
> +        """
Please add the parameters to the docstring as "Args:" section.

2024-04-26 11:05 UTC, jkppr commented on timesketch/api/v1/resources/nl2q.py
> +        """
Please add the parameters to the docstring as "Args:" section.

2024-04-26 11:05 UTC, jkppr commented on timesketch/api/v1/resources/nl2q.py
> +        """
Please add the parameters to the docstring as "Args:" section.

2024-04-26 11:05 UTC, jkppr commented on timesketch/api/v1/resources/nl2q.py
> +        """
Please add the parameters to the docstring as "Args:" section.

2024-05-08 13:39 UTC, dianakramer commented on data/llms/data_types.csv
Changed the name of the folder.

2024-05-08 13:41 UTC, dianakramer commented on timesketch/api/v1/utils.py
> +    csv_file = current_app.config.get(config_parametre_name)
Added.

2024-05-08 13:44 UTC, dianakramer commented on timesketch/api/v1/resources/nl2q.py
> +            String representing the LLM prediction.
Fixed.

2024-05-08 13:46 UTC, dianakramer commented on timesketch/api/v1/resources/nl2q.py
> +        llm_provider = current_app.config.get("LLM_PROVIDER")
Added.

2024-05-08 13:49 UTC, dianakramer commented on timesketch/api/v1/resources/nl2q.py
> +        data_types = data_type_aggregation[0].values
Added.

2024-05-27 15:27 UTC, jkppr requested changes
Please take care of the comments below.

2024-05-27 15:27 UTC, jkppr commented on timesketch/api/v1/resources_test.py
I have added/updated the unit tests to cover the important cases to catch. Please adjust your API endpoint so that the tests don't fail.

2024-05-27 15:27 UTC, jkppr commented on timesketch/lib/testlib.py
> +    PROMPT_NL2Q = "../../../test_data/nl2q/test_prompt_nl2q"
```suggestion
    DATA_TYPES_PATH = "./test_data/nl2q/test_data_types.csv"
    PROMPT_NL2Q = "./test_data/nl2q/test_prompt_nl2q"
```

2024-05-28 08:56 UTC, dianakramer commented on timesketch/api/v1/resources/nl2q.py
> +        data_types = data_type_aggregation[0]["values"]
Added check/

2024-05-28 09:02 UTC, dianakramer commented on timesketch/api/v1/resources/nl2q.py
> +            )
Fixed.

2024-05-29 09:22 UTC, dianakramer commented on timesketch/api/v1/resources_test.py
All tests pass.

2024-05-30 08:58 UTC, jkppr approved these changes
LGTM

2024-05-30 09:19 UTC, merged