Add timeline selection to visualization editor
google/timesketch pull request #3140
Opened 2024-08-15 11:40 UTC by sydp

**IMPORTANT: All Pull Requests should be connected to an issue, if you don't
have an issue, please start by creating an issue and link it to the PR.**

Please provide enough information so that others can review your pull request:

+ What existing problem does this PR solve?
+ What new feature is being introduced with this PR?
+ Overview of changes to existing functions if required.

**Checks**

- [ ] All tests succeed.
- [ ] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes
(if such).

2024-08-16 09:13 UTC, jkppr requested changes
Overall looking good, thanks for adding those filters.

Please check the comments below.

Additionally, can you add an indicator on what timelines a saved visualization was performed? E.g. looking at this screenshot, it is not clear that the data only comes from the BitsClient timeline if I would not have written it into the title.

![image](https://github.com/user-attachments/assets/2d588b2d-3b27-4e88-aeaa-f35c1142a522)

2024-08-16 09:13 UTC, jkppr commented on timesketch/frontend-ng/src/components/Visualization/VisualizationEditor.vue
> +            :analyzerTimelineId="selectedTImelineIDs"
Loading a sketch with this PR throws the following error on the console:

```
[Vue warn]: Property or method "selectedTImelineIDs" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://v2.vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <TsVisualizationEditor> at src/components/Visualization/VisualizationEditor.vue
       <Visualization> at src/views/Visualization.vue
         <Canvas> at src/views/Canvas.vue
           <VMain>
             <Sketch> at src/views/Sketch.vue
               <VApp>
                 <App> at src/App.vue
                   <Root>
```
Deleting the line should fix it, it was used to pre-select timelines based from the Timeline submenu. We can add that later for visualizations.

```suggestion
```

2024-08-16 09:13 UTC, jkppr commented on timesketch/frontend-ng/src/components/Visualization/VisualizationEditor.vue
Small UX nit: Can you add a filter to the field selection so that it only shows fields available in at least one of the selected Timelines?
Otherwise something like this can happen:
![image](https://github.com/user-attachments/assets/a9d1c3d7-7b21-4158-99da-88ec02d22716)

2024-08-16 20:52 UTC, sydp commented on timesketch/frontend-ng/src/components/Visualization/VisualizationEditor.vue
The field names are currently pulled from the vue state where the field names are cached.  Maybe I am thinking about this wrong but to be able to do this I think there might be two options:
* update the state to store field mappings per index
* have a REST endpoint that can be queried to retrieve field name mappings for given indexes/timelines.

2024-08-16 21:02 UTC, sydp commented
> Overall looking good, thanks for adding those filters.
> 
> Please check the comments below.
> 
> Additionally, can you add an indicator on what timelines a saved visualization was performed? E.g. looking at this screenshot, it is not clear that the data only comes from the BitsClient timeline if I would not have written it into the title.
> 
> ![image](https://private-user-images.githubusercontent.com/99879757/358533270-2d588b2d-3b27-4e88-aeaa-f35c1142a522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDQyODQsIm5iZiI6MTcyMzgwMzk4NCwicGF0aCI6Ii85OTg3OTc1Ny8zNTg1MzMyNzAtMmQ1ODhiMmQtM2IyNy00ZTg4LWFlYWEtZjM1YzExNDJhNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEwMjYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MjFkZWQ3ODVkNjZiNWRhYWQ0NzU4YzE0NTMzMGNjZWE5NGM3MzlmNjY5ZDMzZmQ1MTJjNDYyOGQ5ZjNjY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DZyIih76Zn0zDZ2XaF53yx46wMD7nFSWzaGLZ82Y3R0)


If i understand correctly, we want a separate visual element that displays the underlying timeline being used?   Does this have to be in the chart itself or somewhere else in the UI?  Perhaps we need to design/mock this further before implementing?

In saying that, imho I think this is best left to the analyst (or the analyzer) creating the chart to set the title value to appropriately reflect what is being displayed.   Perhaps an auto-generated (template or GenAI suggested) title based on the field, aggregation and timelines selected could achieve this?

2024-08-19 14:16 UTC, jkppr commented on timesketch/frontend-ng/src/components/Visualization/VisualizationEditor.vue
Good point.
I think we should explore an option to have this information in the store, since it might be use-full for even more use-cases.
But lets do this in a separate PR, since this might be more involved.

2024-08-19 14:24 UTC, jkppr approved these changes
As discussed, we will tackle the open UX topics in a follow-up PR. For now it is more important to get the Timeline filter in for the next release.

2024-08-19 14:24 UTC, merged